services:
  backend:
    build: ./backend
    container_name: atv-webinar-backend
    environment:
      PYTHONUNBUFFERED: "1"
    env_file:
      - ./backend/.env
    ports:
      - "8005:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: atv-webinar-frontend
    ports:
      - "8085:80"
    depends_on:
      - backend
    restart: unless-stopped
